#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  This annotation represents an equivalent to the `format` property in the OpenAPI Specification which 
  you are allowed to define inside a schema definition. It should only be used inside "string" types.

type: string
allowedTargets: TypeDeclaration
displayName: Schema Format (OAS)