#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  This annotation represents an equivalent to the `deprecated` property in the OpenAPI Specification that 
  you are allowed to define for any operation. 

type: boolean
default: false
allowedTargets: Method
displayName: Deprecated (OAS)