#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  OpenAPI 2.0 does support the usage of special characters for schema names that RAML
  does not support for its type system. This annotation stores the original name. 

type: string
allowedTargets: TypeDeclaration
displayName: Original Schema Name (OAS)