#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  This annotation represents an equivalent to the `tag` property in the OpenAPI Specification which 
  you are allowed to define for any operation. 

type: string[]
allowedTargets: Method
displayName: Tags (OAS)