#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  This annotation represents an equivalent to the `^x-` property which 
  is used to define extensions for the OpenAPI Specification. 

type: any
displayName: Extensions (OAS)