#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  This annotation represents an equivalent to the `exclusiveMinimum` property in the OpenAPI Specification which 
  you are allowed to define inside a schema definition.

type: boolean
allowedTargets: TypeDeclaration
displayName: Schema ExclusiveMinimum (OAS)