#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  This annotation represents an equivalent to the `responses` property in the OpenAPI Specification which 
  you are allowed to define at the root of an OpenAPI document.

type: any
allowedTargets: API
displayName: Responses (OAS)