#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  This annotation represents an equivalent to the `allowEmptyValue` property in the OpenAPI Specification which 
  you are allowed to define inside a parameter definition.

type: boolean
displayName: Parameter AllowEmptyValue (OAS)