#%RAML 1.0 Library
annotationTypes:
  namespace:
    description: |
      this annotation type allows you to associate unique identifier with a RAML document. It is expected that
      the value of this annotation is an globally unique string
    type: string
(namespace): http://raml.org/vocabularies/annotations/core
