#%RAML 1.0 AnnotationTypeDeclaration

usage: |
  This annotation represents an equivalent to the `default` property in the OpenAPI Specification which 
  you are allowed to define as a possible response besides the HTTP status code.

type: any
allowedTargets: Method
displayName: Default Responses (OAS)